### ISSUE TITLE
Getting error after clicking to pay button

### ISSUE THREAD

**Issue by gagansharma** [payu-india/PayU-Integration-Kit-ROR#1]
I download the application and run it without making any change. But when I click on "Pay with PayU" button on the shopping cart, I get the below error.  How I can test the PayU in test mode.

![payu](https://cloud.githubusercontent.com/assets/1619793/8954383/e22ca842-3602-11e5-9c46-11a119e70444.png)

**Comment by buoyant** [comment]
Please follow README properly and check once again.

On Wed, Jul 29, 2015 at 3:03 PM, Gagan Sharma <notifications@github.com>
wrote:

> I download the application and run it without making any change. But when
> I click on "Pay with PayU" button on the shopping cart, I get the below
> error. How I can test the PayU in test mode.
>
> [image: payu]
> <https://cloud.githubusercontent.com/assets/1619793/8954383/e22ca842-3602-11e5-9c46-11a119e70444.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/payu-india/PayU-Integration-Kit-ROR/issues/1>.
>



-- 
Regards
Sandeep

-- 


*Disclaimer:*


* "This message is intended only for the use of the addressee and may 
contain information that is privileged, confidential and exempt from 
disclosure under applicable law. If the reader of this message is not the 
intended recipient, or the employee or agent responsible for delivering the 
message to the intended recipient, you are hereby notified that 
any dissemination, distribution or copying of this communication is 
strictly prohibited. If you have received this e-mail in error, please 
notify us immediately by return e-mail and delete this e-mail and all 
attachments from your system."*

**Comment by gagansharma** [comment]
I use key and salt for test environment 
:key => 'JBZaLc', :salt => 'GQs7yium'

but it still giving the same error.

**Comment by gagansharma** [comment]
Can you tell what values need to be given for KEY and SALT in the test environment

**Comment by buoyant** [comment]
Are you are giving the right ones which you got from payu.

Please send backtrace from rails console while you are facing this
exception.

On Thu, Jul 30, 2015 at 11:02 AM, Gagan Sharma <notifications@github.com>
wrote:

> Can you tell what values need to be given for KEY and SALT in the test
> environment
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/payu-india/PayU-Integration-Kit-ROR/issues/1#issuecomment-126190305>
> .
>



-- 
Regards
Sandeep

-- 


*Disclaimer:*


* "This message is intended only for the use of the addressee and may 
contain information that is privileged, confidential and exempt from 
disclosure under applicable law. If the reader of this message is not the 
intended recipient, or the employee or agent responsible for delivering the 
message to the intended recipient, you are hereby notified that 
any dissemination, distribution or copying of this communication is 
strictly prohibited. If you have received this e-mail in error, please 
notify us immediately by return e-mail and delete this e-mail and all 
attachments from your system."*

**Comment by emaillenin** [comment]
I am getting the below error:

````
> cannot load such file -- active_merchant/billing/integrations
````

while calling:

````
require 'active_merchant_payu_in'
````

**Comment by buoyant** [comment]
@emaillenin Please follow README
