### ISSUE TITLE
Our Key and salt not working

### ISSUE THREAD

**Issue by manishkongari** [payu-india/PayU-Integration-Kit-ROR#3]
'8I6weUA8', 'cdpg93pIo6', key and salt respectively please check every detail is filled in the payu 
ps: it is giving secure url itself on my website.
admin panel
We are getting this error

SORRY!
We were unable to process your payment

Error Reason
You seem to be using an incorrect key or salt value.

Corrective Action
Please note that this is PayU's Live (Production) Environment - https://secure.payu.in/_payment, but the key (8I6weUA8) you are using in the transaction is not a Live (Production) Environment key.

Please ensure that if you are hitting PayU's Production Environment, you must use only the Production (Live) key and salt in the transaction request - which have been shared with you by the PayU Account Manager.

How to get the correct Live key/alias and salt?
Your PayU Account Manager would have shared the Live key/alias and salt values with you on your registered email-ID. The mail would be in the below format:
...
Dear Merchant,
Your login details.
Thank you for choosing PayUbiz.
User Name: <name>
Login Alias: <alias>
Password Link: <Create New Password>

**Comment by buoyant** [comment]
Please check with your sales dept for live key and salt.

**Comment by aditraj** [comment]
My Key and salt not working in Asp.net c#
this error are showing

SORRY!
We were unable to process your payment

Error Reason
You seem to be using an incorrect key or salt value.

Corrective Action
Please note that this is PayU's Live (Production) Environment - https://secure.payu.in/_payment, but the key (EqTdBFAD) you are using in the transaction is not a Live (Production) Environment key.

Please ensure that if you are hitting PayU's Production Environment, you must use only the Production (Live) key and salt in the transaction request - which have been shared with you by the PayU Account Manager.

How to get the correct Live key/alias and salt?
Your PayU Account Manager would have shared the Live key/alias and salt values with you on your registered email-ID. The mail would be in the below format:

...
Dear Merchant,
Your login details.
Thank you for choosing PayUbiz.
User Name:	<name>
Login Alias:	<alias>
Password Link:	<Create New Password>

please sent me solution on this id (aditraj1@gmail.com)

**Comment by manishkongari** [comment]
Thanks for your prompt reply.

On Mon, Jan 23, 2017 at 4:28 PM, aditraj <notifications@github.com<mailto:notifications@github.com>> wrote:

My Key and salt not working in Asp.net c#
this error are showing

SORRY!
We were unable to process your payment

Error Reason
You seem to be using an incorrect key or salt value.

Corrective Action
Please note that this is PayU's Live (Production) Environment - https://secure.payu.in/_payment, but the key (EqTdBFAD) you are using in the transaction is not a Live (Production) Environment key.

Please ensure that if you are hitting PayU's Production Environment, you must use only the Production (Live) key and salt in the transaction request - which have been shared with you by the PayU Account Manager.

How to get the correct Live key/alias and salt?
Your PayU Account Manager would have shared the Live key/alias and salt values with you on your registered email-ID. The mail would be in the below format:

...
Dear Merchant,
Your login details.
Thank you for choosing PayUbiz.
User Name:
Login Alias:
Password Link:

please sent me solution on this id (aditraj1@gmail.com<mailto:aditraj1@gmail.com>)

**Comment by sammirza3** [comment]
same is happening with me but it works with test key and salt.

**Comment by sammirza3** [comment]
Hey guys just make sure you are posting service provider attribute. To check this on your error page open the inspect element tab and click on network option check are posting service provider attribute or not. if not then add this line in your form and check it it will work. "<input type="hidden" name="service_provider" value="payu_paisa" size="64" /><br>"

**Comment by Arvind8858** [comment]
Any solution for this ?

**Comment by sammirza3** [comment]
give the details so that we can figure out the bug.

**Comment by aninditaelagoon** [comment]
I am using test credential, but still giving me below error
=====================================
Error Reason
You seem to be using an incorrect key or salt value.

Corrective Action
Please note that this is PayU's Test Environment - https://test.payu.in/_payment , but the key (EtGsgPrz) you are using is not a Test Environment key.

Please ensure that you are using correct key and salt in the transaction request. Please note that key and salt are alphanumeric string values which are provided by PayU.

Value of a sample key - gtKFFx
Value of a sample salt - eCwWELxi

In case you haven't received the key/salt yet, please contact your Account Manager at PayU.

**Comment by sammirza3** [comment]
apply your key on below code just change the key and salt.
https://github.com/sammirza3/samPayu/tree/master/samPayUDjangoApp
